* nix stuff

I used to use [[http://nixos.org/nix/][nix]] in two places: running NixOS on a little acer
chromebook, and the nix package manager on my mac.

Now, I just run it on my mac. But I'm getting it installed on a
desktop linux machine too. Just need to get the kernel to talk to the
Wifi card...

- The NixOS setup lives in [[./nixos][nixos]]. This is outdated.
- Common configuration is in [[./nixpkgs][nixpkgs]] in =config.nix=. This defines a
  set of packages I want to be in my environment called =devEnv=.

** mac workflow

*** (re)installing the environment defined in =config.nix=:

#+begin_src sh
./scripts/build-nix-env
#+end_src

*** upgrading

Just run the following in the project root:

#+begin_src sh
niv update nixpkgs
#+end_src

*** collecting garbage

nix artifacts hang around long after you've finished using them, and
will use a bit of space. to clean:

#+begin_src sh
nix-env --delete-generations old
nix-collect-garbage
#+end_src

or to remove everything not in a profile,

#+begin_src sh
nix-collect-garbage -d
#+end_src

*** installing ad-hoc package

#+begin_src sh
nix-env -iA nixpkgs.python
#+end_src

*** seeing what's installed

#+begin_src sh :export both
nix-env -q
#+end_src

*** querying packages

#+begin_src bash :export both
nix-env -qa '*' | grep postgresql
#+end_src

#+RESULTS:
| nixpkgs.postgresql90    | postgresql-9.0.23        |
| nixpkgs.postgresql91    | postgresql-9.1.19        |
| nixpkgs.postgresql92    | postgresql-9.2.14        |
| nixpkgs.postgresql93    | postgresql-9.3.10        |
| nixpkgs.postgresql      | postgresql-9.4.5         |
| nixpkgs.postgresql_jdbc | postgresql-jdbc-9.3-1100 |

