#!/usr/bin/env ruby

[
  "gemrc",
  "screenrc",
  "gitconfig",
  "vim/vimrc",
  "vim",
  "bashrc",
  "ghci",
  "tmux.conf",
  "mutt_color",
  "emacs.d",
  "xmonad"
].each do |conf|
  filename = conf.match(/\/?([^\/]+)$/)[1]
  command = "ln -s #{File.expand_path(conf)} ~/.#{filename}"
  unless File.exists?(File.expand_path("~/.#{filename}"))
    puts "Linking #{conf}..."
    system command
  end
  # hushlogin: prevent the system from searching logs
  # to find the last time logged in.
  system "touch ~/.hushlogin"
end

unless File.exists?(File.expand_path("~/.dotfiles"))
  system "ln -s #{File.expand_path('.')} ~/.dotfiles"
end

unless File.exists?(File.expand_path("~/.nixpkgs/config.nix"))
  system "mkdir -p ~/.nixpkgs"
  system "ln -s #{File.expand_path("nix/mjhoy/config.nix")} ~/.nixpkgs/config.nix"
end
