#!/usr/bin/env ruby

[
  "gemrc",
  "screenrc",
  "gitconfig",
  "vim/vimrc",
  "vim",
  "bashrc",
  "ghci"
].each do |conf|
  filename = conf.match(/\/?(\w+)$/)[1]
  command = "ln -s #{File.expand_path(conf)} ~/.#{filename}"
  unless File.exists?(File.expand_path("~/.#{filename}"))
    puts "Linking #{conf}..."
    system command
  end
  # hushlogin: prevent the system from searching logs
  # to find the last time logged in.
  system "touch ~/.hushlogin"
end
