* mjhoy/dotfiles

My configuration. I'm currently working primarily on my [[./emacs.d][emacs config]]
and, more recently, my [[./nix][nix]] setup.

There's also some Haskell, Ruby, git, and bash configuration.

I mostly run this on my Mac OS X machine and in a NixOS VM.

** getting the source

If you really want it, make sure to clone with `--recursive` to check
out submodules.

#+begin_src sh
git clone --recursive https://github.com/mjhoy/dotfiles.git
#+end_src

Or, run =make= after doing a normal clone to init and update git
submodules:

#+begin_src sh
cd dotfiles
make
#+end_src

** installing symlinks to $HOME

Running =make install= will generate the appropriate symbolic links
(e.g., ~/.vimrc -> dotfiles/vim/vimrc, etc):

#+begin_src sh
make install
#+end_src

Running =make install-linux= will do the same and include
linux-specific configuration (such as .Xresources).

** nix/NixOS

See [[./nix/nixos/README.org][nix/nixos/README.org]] for details on my attempt to set up a NixOS
vm for all my development work.

But these days I am just using macOS with nixpkgs. You can find my
config for this in [[./nix/nixpkgs][nix/nixpkgs]].

** license

MIT. See the [[./LICENSE][LICENSE]] file.
