# mjhoy's vim setup
# Based on Ben Bleything's script. http://github.com/bleything/dotvim

require 'pathname'

task :default do
  puts "Hi! All this Rakefile can do right now is update the bundles:"
  puts # blank line
  puts "  $ rake update:bundles"
end

namespace :update do

  BUNDLES = {
    # plugins
    :git          => "git://github.com/tpope/vim-git.git",
    :fugitive     => "git://github.com/tpope/vim-fugitive.git",
    :ragtag       => "git://github.com/tpope/vim-ragtag.git",
    :rails        => "git://github.com/tpope/vim-rails.git",
    :coffeescript => "git://github.com/kchmck/vim-coffee-script.git",
    :gundo        => "git://github.com/sjl/gundo.vim.git",
    :jade         => "git://github.com/vim-scripts/jade.vim.git",
    :scss         => "git://github.com/cakebaker/scss-syntax.vim.git",
    :vimroom      => "git://github.com/mikewest/vimroom.git",
    :racket       => "git://github.com/wlangstroth/vim-racket.git",
    :solarized    => "git://github.com/altercation/vim-colors-solarized.git",
    :ctrl_p       => "git://github.com/kien/ctrlp.vim.git",
    :go           => "git://github.com/jnwhiteh/vim-golang.git"
    # syntax definitions
    # ...
  }

  desc "update any bundles defined in the Rakefile"
  task :bundles do

    bundle_home = Pathname.new( ENV['HOME'] ) + '.vim' + 'bundle'
    mkdir_p bundle_home

    BUNDLES.sort_by {|k,v| k.to_s }.each do |bundle, location|
      target_path = bundle_home + bundle.to_s

      puts "*" * 72
      puts "*** Installing #{bundle} to #{target_path} from #{location}"
      puts # blank line

      rm_rf target_path

      case location.match( /^(.*?):/ )[1]
      when 'git'
        sh "git clone #{location} #{target_path} > /dev/null"
        rm_rf target_path + '.git'
      when 'http'
        mkdir_p target_path
        sh "cd #{target_path} && curl -s '#{location}' | tar zx -"
      end

      docdir = target_path + 'doc'
      if docdir.exist?
        puts "doc dir exists; tagging"
        sh "vim -u NONE -esX -c 'helptags #{docdir}' -c quit"
      end

      puts # blank line
    end
  end # task :bundles

end # namespace :update

