" This option goes first because it may have side-effects.
set nocompatible

" Pathogen loads all plugins in ~/.vim/bundle
call pathogen#infect()

syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

runtime macros/matchit.vim        " Load the matchit plugin.
runtime ftplugin/man.vim          " Turn on manpages (:Man)

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set nowrap                        " Turn off line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location

set clipboard=unnamed             " Use the Mac OS X clipboard

set pastetoggle=<F2>              " To turn off indenting, etc, while pasting.

" 2 spaces for tabs.
set tabstop=2
set shiftwidth=2
set expandtab

" no coffeescript trailing space error indication
let coffee_no_trailing_space_error = 1

" Use magic
set magic

set laststatus=2                  " Show the status line all the time
" Useful status information at bottom of screen
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P

" Use 256 colors.
set t_Co=256

" Or use vividchalk
colorscheme mjh

" Map + and - keys to resize the split window.
nnoremap <silent> + :exe "resize " . (winheight(0) * 3/2)<CR>
nnoremap <silent> - :exe "resize " . (winheight(0) * 2/3)<CR>

" Use comma for leader.
let mapleader=","

" Double leader switches to last buffer.
nnoremap <leader><leader> <c-^>

" Gundo plugin for easy undo/redo tree browsing
" Requires Vim 7.3
map <leader>gu :GundoToggle<cr>

" Map ,e and ,v to open files in the same directory as the current file
" From Gary Bernhardt's vimrc
cnoremap %% <C-R>=expand('%:h').'/'<cr>
map <leader>e :edit %%
map <leader>v :view %%

" <C-L> to clear search
if exists(":nohls")
  nnoremap <silent> <C-L> :nohls<CR><C-L>
endif

" Automatic fold settings for specific files. Uncomment to use.
autocmd FileType ruby set foldmethod=syntax
" autocmd FileType css  setlocal foldmethod=indent shiftwidth=2 tabstop=2

" Gemfiles are ruby files
autocmd BufRead,BufNewFile Gemfile set filetype=ruby
" *.md -> markdown files
autocmd BufRead,BufNewFile *.md set filetype=markdown

" DiffOrig -- diff original file w/ buffer in new vert
" from help :DiffOrig
" (http://vimdoc.sourceforge.net/htmldoc/diff.html#:DiffOrig)
command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis | wincmd p | diffthis

" No thanks for flying
let &titleold=''
