;;;; init.el / @mjhoy

(setq user-full-name "Michael Hoy"
      user-mail-address "mjh@mjhoy.com")

(add-to-list 'load-path
             (expand-file-name "lisp" user-emacs-directory))
(add-to-list 'load-path
             (expand-file-name "site-lisp" user-emacs-directory))

(require 'init-standard)
(require 'init-packages)
(require 'init-diminish)
(require 'init-ui)
(require 'init-theme)
(require 'init-org)
(require 'init-erc)
(require 'init-windmove)
(require 'init-projectile)
(require 'init-ibuffer)
(require 'init-dired)
(require 'init-uniquify)
(require 'init-company)
(require 'init-mu4e)
(require 'init-yas)
(require 'init-sql)
(require 'init-flycheck)
(require 'init-helm)
(require 'init-magit)
(require 'init-restclient)
(require 'init-scheme)
(require 'init-ruby)
(require 'init-rust)
(require 'init-javascript)
(require 'init-haskell)
(require 'init-c)
(require 'init-nasm)
(require 'init-php)
(require 'init-web-mode)
(require 'init-css)
(require 'init-project-archetypes)
(require 'init-term)
(require 'init-misc)
