#!/bin/bash
#
# This script checks out the latest nixpkgs and attempts to build my
# developer environment against it. If all goes well, it will push an
# update to the mjh-mbp branch.

set -eoux pipefail

echo "Building devEnv"
nix build --no-link nixpkgs.devEnv

echo "Building hie"
nix build --no-link nixpkgs.hie

echo "Building nix"
nix build --no-link nixpkgs.nix

echo "Installing"
nix-env -iA nixpkgs.devEnv
nix-env -iA nixpkgs.hie
nix-env -iA nixpkgs.nix
