#!/bin/bash
#
# This script checks out the latest nixpkgs and attempts to build my
# developer environment against it. If all goes well, it will push an
# update to the mjh-mbp branch.

set -eoux pipefail

echo "Building devEnv"
nix-build --no-link --show-trace '<nixpkgs>' -A devEnv

echo "Building nix"
nix-build --no-link '<nixpkgs>' -A nix

echo "Installing"
nix-env -i devEnv
nix-env -i nix
