#!/bin/bash
#
# This script checks out the latest nixpkgs and attempts to build my
# developer environment against it. If all goes well, it will push an
# update to the mjh-mbp branch.

LOCAL_REMOTE=mjhoy
LOCAL_BRANCH=mjh-mbp
UPDATE_REMOTE=origin
UPDATE_BRANCH=nixpkgs-20.03-darwin

set -eoux pipefail

cleanup() {
    cd $HOME/.dotfiles/nixpkgs
    git checkout $LOCAL_BRANCH
    echo "nixpkgs set to $LOCAL_BRANCH branch"
}
trap cleanup 0

cd $HOME/.dotfiles/nixpkgs

if ! git status | grep 'working tree clean'
then echo 'Clean up working directory first.'; exit 1
fi

git checkout $UPDATE_BRANCH
git pull $UPDATE_REMOTE

echo "Building devEnv"
nix build --no-link nixpkgs.devEnv

echo "Building nix"
nix build --no-link nixpkgs.nix

git checkout $LOCAL_BRANCH
git merge $UPDATE_BRANCH

nix-env -iA nixpkgs.devEnv
nix-env -iA nixpkgs.nix

TAG_NAME="mjh-v$(date +%F)"
TAG_MSG="$(date +%F): update with latest $UPDATE_BRANCH"
git tag -m "$TAG_MSG" $TAG_NAME
git push $LOCAL_REMOTE $LOCAL_BRANCH --tags
