#!/bin/bash

set -eoux pipefail

# The following won't get auto-updated.
SKIP_SUBMODULES="yaml markdown-mode"

export SKIP_SUBMODULES

function update() {
    if [[ " $SKIP_SUBMODULES " =~ " $name " ]]; then
        echo "skipping $name as set in SKIP_SUBMODULES"
        return 0
    fi
    branch=$(git rev-parse --abbrev-ref HEAD)
    git fetch origin
    local_sha=$(git rev-parse ${branch})
    remote_sha=$(git rev-parse origin/${branch})
    if [ ! "$local_sha" == "$remote_sha" ]; then
        cd $toplevel
        date=$(date "+%Y-%m-%d")
        top_branch=$(git rev-parse --abbrev-ref HEAD)
        update_branch=update-${name}-${date}
        git checkout -b $update_branch
        submodule_git_url=$(git config --file=.gitmodules submodule.${name}.url)
        submodule_http_url=${submodule_git_url/git@/https://}
        submodule_http_url=${submodule_http_url/.com:/.com/}
        submodule_http_url=${submodule_http_url/.git//}
        diff_url=${submodule_http_url}/compare/${local_sha}...${remote_sha}
        git submodule update --remote -- $sm_path
        git add $sm_path
        git commit -m "bump ${name} ${date}"
        git push origin $update_branch -u
        gh pr create --draft --title "bump ${name} ${date}" --body "Compare: ${diff_url}" -B $top_branch
        git checkout $top_branch
    fi
}

export -f update

date=$(date "+%Y-%m-%d")
main_update_branch=update-emacs-packages-${date}
git checkout -b $main_update_branch
git push origin $main_update_branch -u

git submodule foreach 'update'
