name: "Update submodules"
on:
  workflow_dispatch:
  schedule:
    # 12 UTC Wednesdays
    - cron: '0 12 * * WED'
jobs:
  update:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        ./scripts/update-submodules
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
