name: "Update"
on:
  schedule:
    # First day of the month at 9 UTC
    - cron: '0 9 1 * *'
jobs:
  update:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=${{ github.workspace }}/nixpkgs
        install_url: https://releases.nixos.org/nix/nix-2.8.1/install
    - run: make install
    - uses: cachix/cachix-action@v12
      with:
        name: mjhoy
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        extraPullNames: nix-community
    - run: ./scripts/build-nix-env
    - run: ./scripts/update-nixpkgs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
